backend:
  image: "ghcr.io/yourorg/mirador-backend:0.1.0"
  replicas: 2
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: NODE_ENV
      value: production
    - name: PORT
      value: "8080"
    - name: CORS_ORIGIN
      value: "https://your.domain"
    - name: REDIS_HOST
      value: valkey
    - name: REDIS_PORT
      value: "6379"
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: mirador-secrets
          key: DATABASE_URL

frontend:
  image: "ghcr.io/yourorg/mirador-frontend:0.1.0"
  replicas: 2
  resources:
    limits:
      cpu: "300m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "your.domain"

