worker_processes  auto;
events { worker_connections 1024; }
http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile        on;
  keepalive_timeout  65;
  gzip on;
  gzip_types text/plain application/javascript application/x-javascript text/javascript text/xml text/css application/json image/svg+xml;
  server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    location / {
      try_files $uri $uri/ /index.html;
    }
    location ~* \.(?:js|css|svg|woff2?)$ {
      expires 7d;
      add_header Cache-Control "public, max-age=604800, immutable";
    }
  }
}

