apiVersion: v1
kind: Service
metadata:
  name: mirador-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/api/metrics"
spec:
  type: ClusterIP
  selector:
    app: mirador-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
