apiVersion: batch/v1
kind: CronJob
metadata:
  name: mirador-mysql-backup
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: mysql:8.4
              env:
                - name: MYSQL_PWD
                  valueFrom:
                    secretKeyRef:
                      name: mirador-secrets
                      key: MYSQL_ROOT_PASSWORD
              command:
                - /bin/sh
                - -c
                - |
                  mysqldump -h mysql -u root mirador > /backup/mirador-$(date +%F).sql
              volumeMounts:
                - name: backup
                  mountPath: /backup
          volumes:
            - name: backup
              emptyDir: {}
