apiVersion: batch/v1
kind: Job
metadata:
  name: mirador-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: {{ .Values.backend.image }}
          command: ["npx","prisma","migrate","deploy"]
          env: {{- toYaml .Values.backend.env | nindent 12 }}
